#!/usr/bin/env bash

# Open dmenu list of songs/videos and play with mpv
# Ctrl+Alt+M

FOLDER="/media/sam/inhdd/songs"

openvid() {

    NAME=$(
        {
            echo "🎲 Random"
            ls "$FOLDER"
        } | dmenu -i -c -l 15
    ) || exit 0

    [ -z "$NAME" ] && exit 0

    if [ "$NAME" = "🎲 Random" ]; then
        NAME=$(find "$FOLDER" -maxdepth 1 -type f | shuf -n1)
        mpv --force-window --idle --loop --geometry=660x360+0+0 --ontop "$NAME" >/dev/null 2>&1 &
    else
        mpv --force-window --idle --loop --geometry=640x360+0+0 --ontop "$FOLDER/$NAME" >/dev/null 2>&1 &
    fi
}

openvid
