#!/usr/bin/env bash 

# opens kill menu and asks for any service to be killed 

process=$(ps -u "$USER" -o pid=,comm= | dmenu -i -c -l 15 -p "Kill process:") 
[ -z "$process" ] && exit 0 
pid=$(awk '{print $1}' <<< "$process")
kill "$pid"

