#!/usr/bin/env bash

# dmenu prompts options to select a .md file to edit , also new can create a new .md file after
# asking for name , give default date name if the name is not given 
# shortcut :  ctrl+alt+n 


# Directory where notes are stored
folder="$HOME/notes"

# Create the folder if it doesn't exist
mkdir -p "$folder"

newnote() {
	name="$(echo "" | dmenu -c -sb "#a3be8c" -nf "#d8dee9" -p "Enter a name: " <&-)" || exit 0 #: "${name:=$(date +%F_%T | tr ':' '-')}" 

    # If the user didn't type anything, use the current date and time
    [[ -z "$name" ]] && name=$(date +"%F_%H-%M-%S")

    # Add the extension if it's missing
    [[ "$name" != *.md ]] && name="$name.md"

 	setsid -f terminator -e "nvim \"$folder/$name\".md" >/dev/null 2>&1
}

selected() {
    choice=$(
        {
            echo "New"
            find "$folder" -maxdepth 1 -type f -name "*.md" -printf "%f\n" | sort
        } | dmenu -c -l 8 -i -p "Choose note:"
    ) || exit 0

    case "$choice" in
        New)
            newnote
            ;;
        *.md)
            setsid -f terminator -e "nvim \"$folder/$choice\"" >/dev/null 2>&1
            ;;
        *)
            exit 0
            ;;
    esac
}

selected
